# The licence table in README.md, rendered from what the flake actually pulls in rather
# than kept by hand. Two sources, because only one of them can be introspected:
#
#   - the devshell's package list  -> read straight off each derivation's `meta`
#   - inputs consumed as source    -> declared in nix/lib/vendored.nix, since a plain
#                                     source tree has no `meta` to read
#
# `nix run .#update-licenses` splices the result into README.md; nix/checks/licenses.nix
# fails when the two disagree, so the table cannot quietly go stale.
{
  pkgs,
  inputs,
  perSystem,
  ...
}:
let
  inherit (pkgs) lib;
  vendored = import ../lib { };

  # The devshell is where the third-party tools are actually chosen, so its package list
  # is the source of truth. mkShellNoCC puts `packages` into nativeBuildInputs.
  shellPackages = (import ../devshell.nix { inherit pkgs inputs perSystem; }).nativeBuildInputs;

  licenceOf =
    p:
    let
      l = p.meta.license or null;
      name = x: x.spdxId or (x.shortName or "unknown");
    in
    if l == null then
      "unknown"
    else if builtins.isList l then
      lib.concatMapStringsSep " / " name l
    else
      name l;

  fromPackage = p: {
    name = p.pname or (lib.getName p);
    version = p.version or "";
    license = licenceOf p;
    description = p.meta.description or "";
    homepage = p.meta.homepage or "";
  };

  fromSource = name: d: {
    inherit name;
    version = ""; # pinned by flake.lock, not versioned upstream
    inherit (d) license description homepage;
  };

  packages = map fromPackage shellPackages;
  sources = lib.mapAttrsToList fromSource vendored.sources;

  # A copyleft licence is the one a reader needs to notice, so it is called out rather
  # than left to be spotted in a column.
  strong = l: lib.hasPrefix "AGPL" l || lib.hasPrefix "GPL" l;

  row =
    e:
    let
      label = if e.homepage != "" then "[${e.name}](${e.homepage})" else e.name;
      ver = if e.version != "" then " ${e.version}" else "";
      lic = if strong e.license then "**${e.license}**" else e.license;
    in
    "| ${label}${ver} | ${lic} | ${e.description} |";

  byName = builtins.sort (a: b: a.name < b.name);

  table =
    entries:
    lib.concatStringsSep "\n" (
      [
        "| | Licence | What it is |"
        "|---|---|---|"
      ]
      ++ map row (byName entries)
    );

  body = ''
    <!-- Generated by `nix run .#update-licenses`. Do not edit by hand. -->

    ### On PATH in the devshell

    ${table packages}

    ### Vendored as source (FreeCAD addons, OpenSCAD libraries)

    ${table sources}
  '';
in
pkgs.writeText "licenses.md" body
